
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import javazoom.jl.player.advanced.AdvancedPlayer;
import javazoom.jl.player.advanced.PlaybackEvent;
import javazoom.jl.player.advanced.PlaybackListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Josue Gavidia
 */
public class GUIMP3 extends javax.swing.JFrame {

    /**
     * Creates new form GUIMP3
     */
    private MusicManager m;
    public ArrayList ListaCanciones = new ArrayList();
    public Player Reproductor;
    public AdvancedPlayer player;
    public boolean pausa;
    private ByteArrayOutputStream bytes;
    private int ultimaPausa;

    public GUIMP3() throws IOException {
        m = new MusicManager();
        pausa = false;
        bytes = new ByteArrayOutputStream();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LISTA = new javax.swing.JList<>();
        btnplay = new javax.swing.JButton();
        PAUSA = new javax.swing.JButton();
        btnstop1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SONG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DURACION = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ARTISTA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadd.setBackground(new java.awt.Color(0, 0, 0));
        btnadd.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Añadir cancion");
        btnadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, 50));

        jScrollPane2.setViewportView(LISTA);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 580, 460));

        btnplay.setBackground(new java.awt.Color(0, 0, 0));
        btnplay.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnplay.setForeground(new java.awt.Color(255, 255, 255));
        btnplay.setText("Play");
        btnplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 84, 68));

        PAUSA.setBackground(new java.awt.Color(0, 0, 0));
        PAUSA.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        PAUSA.setForeground(new java.awt.Color(255, 255, 255));
        PAUSA.setText("Pause");
        PAUSA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        PAUSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAUSAActionPerformed(evt);
            }
        });
        jPanel1.add(PAUSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 84, 68));

        btnstop1.setBackground(new java.awt.Color(0, 0, 0));
        btnstop1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnstop1.setForeground(new java.awt.Color(255, 255, 255));
        btnstop1.setText("Stop");
        btnstop1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        btnstop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstop1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnstop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 84, 68));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SONG.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SONG.setText("Cancion");
        jPanel2.add(SONG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 320, 30));

        jLabel1.setText("0:00");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        DURACION.setText("Time");
        jPanel2.add(DURACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, -1));

        jLabel2.setText("PORTADA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 90, 90));

        ARTISTA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ARTISTA.setText("Artista");
        jPanel2.add(ARTISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 680, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        AñadirCancion();
        ActualizarLista();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed

        Reproducir();


    }//GEN-LAST:event_btnplayActionPerformed

    private void PAUSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAUSAActionPerformed

    }//GEN-LAST:event_PAUSAActionPerformed

    private void btnstop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstop1ActionPerformed
        if (this.Reproductor != null) {
            Reproductor.close();
        } else {
            JOptionPane.showMessageDialog(null, "Algo salio mal");
        }
    }//GEN-LAST:event_btnstop1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIMP3().setVisible(true);
                } catch (IOException ex) {
                    System.out.println(ex.getCause());
                }
            }
        });
    }

    public void AñadirCancion() {
        m.Add(ARTISTA, SONG, DURACION, this);
//        ActualizarLista();
    }

    public void ActualizarLista() {

        ListaCanciones = m.getCanciones();
        DefaultListModel model = new DefaultListModel();

        for (int i = 0; i < ListaCanciones.size(); i++) {
            int x = i + 1;
            model.add(i, x + "- " + ((File) ListaCanciones.get(i)).getName());

        }
        LISTA.setModel(model);

    }

    File Cancion1;
    static int hola = 0;

    public void Reproducir() {

        if (hola == 0) {
            try {
                int CancionSeleccionada = LISTA.getSelectedIndex();
                Cancion1 = (File) this.ListaCanciones.get(CancionSeleccionada);
                FileInputStream song = new FileInputStream(Cancion1);
                BufferedInputStream song2 = new BufferedInputStream(song);
                Reproductor = new javazoom.jl.player.Player(song2);
                hola = 1;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: eliga una cancion valida");
            }

            new Thread() {
                @Override
                public void run() {

                    try {
                        Reproductor.play();

                    } catch (Exception e) {

                    }
                }

            }.start();

        } else {

            Reproductor.close();
            hola = 0;
            Reproducir();

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ARTISTA;
    private javax.swing.JLabel DURACION;
    private javax.swing.JList<String> LISTA;
    private javax.swing.JButton PAUSA;
    private javax.swing.JLabel SONG;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnstop1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
